### ISSUE TITLE
Novels that have been taken off the shelves cannot be downloaded

### ISSUE THREAD

**Issue by Si-JiX** [novel-rs/cli#101]
As per the question. If the novel is taken off the shelves, it will prompt "cannot be found". This issue should be related to the API used by the author. If it cannot be solved, I can provide a method, but I don't want many people to know. (Also, is the author Chinese? If so, we can communicate directly in Chinese.)

**Comment by TerakomariGandesblood** [comment]
> As per the question. If the novel is taken off the shelves, it will prompt "cannot be found". This issue should be related to the API used by the author. If it cannot be solved, I can provide a method, but I don't want many people to know. (Also, is the author Chinese? If so, we can communicate directly in Chinese.)

It is expected behavior that a novel that has been taken down cannot be downloaded. If you have any ideas please contact me via Telegram, the link is on my profile. Also, I'm Chinese

**Comment by TerakomariGandesblood** [comment]
Any ideas?
@Si-JiX
