### ISSUE TITLE
Support for new websites

### ISSUE THREAD

**Issue by tim20040723** [novel-rs/cli#105]
Hello! I would like to know if this project will implement crawlers for XiRang  Novels, Youdu Novel Network, and Duyuedu in the future.
They're  https://xrzww.com/.https://youdubook.com/.https://www.duread.cn/.

**Comment by TerakomariGandesblood** [comment]
> Hello! I would like to know if this project will implement crawlers for XiRang Novels, Youdu Novel Network, and Duyuedu in the future.
> They're https://xrzww.com/.https://youdubook.com/.https://www.duread.cn/.

I have no plans to support these sites at the moment. You can take a look [here](https://github.com/404-novel-project/novel-downloader), this project should support these websites. You can read about future support plans [here](https://github.com/novel-rs/api/issues/18).
