### ISSUE TITLE
Base64Error

### ISSUE THREAD

**Issue by YosakuraTohu** [novel-rs/cli#114]
```bash
[kinare@kinare Novel]$ ./novel-cli download -s sfacg -f pandoc 166787
Error: 
   0: Base64Error

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

`cargo test --test download` version: 0.5.0
[test.txt](https://github.com/novel-rs/cli/files/12261159/test.txt)

environment:
```bash
OS: Arch Linux x86_64
Kernel: 6.4.7-arch1-2
Shell: bash 5.1.16
```

**Comment by TerakomariGandesblood** [comment]
See [0.5.0](https://github.com/novel-rs/cli/releases/tag/0.5.0). You need to manually delete the previously saved cookie files and database files.
@YosakuraTohu

**Comment by YosakuraTohu** [comment]
谢谢，问题已解决，是我没认真看Changelog
