### ISSUE TITLE
cannot search novel from ciweimao

### ISSUE THREAD

**Issue by linyisan** [novel-rs/cli#141]

**Comment by TerakomariGandesblood** [comment]
Can you provide more detailed information?

**Comment by linyisan** [comment]
> Can you provide more detailed information?

I type as follow,and it throw an excception

`  .\novel-cli.exe search -s ciweimao 型月 --backtrace full
Error:
   0: Base64Error

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: BaseThreadInitThunk<unknown>
      at <unknown source file>:<unknown line>
   2: RtlUserThreadStart<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.`

**Comment by TerakomariGandesblood** [comment]
> > Can you provide more detailed information?
> 
> I type as follow,and it throw an excception
> 
> ![1](https://user-images.githubusercontent.com/31615265/280791529-56b39e98-7fdf-4814-a43e-4770767bf195.jpg)

My guess is that the previous files were not deleted
> Since this version starts to use encrypted database, cookie files and config files, you need to manually delete the old files, and the file path can be obtained using novel-cli -V; due to changing the name of the saved password, the previously saved password will become invalid .

**Comment by linyisan** [comment]
> > > Can you provide more detailed information?
> > 
> > 
> > I type as follow,and it throw an excception
> > ![1](https://user-images.githubusercontent.com/31615265/280791529-56b39e98-7fdf-4814-a43e-4770767bf195.jpg)
> 
> My guess is that the previous files were not deleted
> 
> > Since this version starts to use encrypted database, cookie files and config files, you need to manually delete the old files, and the file path can be obtained using novel-cli -V; due to changing the name of the saved password, the previously saved password will become invalid .

After deleting the files in the path as the commond shows, it works.
