### ISSUE TITLE
Someting wrong when there are some emoji in the title

### ISSUE THREAD

**Issue by tim20040723** [novel-rs/cli#144]
When I use sfacg :download 590959 --source sfacg --format pandoc.
![屏幕截图 2024-01-03 002926](https://github.com/novel-rs/cli/assets/108276181/8ee63740-a9a6-4524-8e2f-29d67dd28a18)
I'm sure I bought the whole book,but this happened.I think its because of the emoji in the title.
The same error in the old programe.
![屏幕截图 2024-01-03 003337](https://github.com/novel-rs/cli/assets/108276181/5095f936-09eb-4ea3-96ac-21539ee8d407)

**Comment by TerakomariGandesblood** [comment]
I think this is a bug of sfacg. I also cannot browse this chapter on the mobile client. I will modify the program in the future to ignore HTTP 403 errors.
@tim20040723

**Comment by TerakomariGandesblood** [comment]
By the way, this problem has nothing to do with emoji.

**Comment by TerakomariGandesblood** [comment]
Already solved
