### ISSUE TITLE
Can't type password. 

### ISSUE THREAD

**Issue by FisheadInLukeWarmWater** [novel-rs/cli#145]
![won't let me ](https://github.com/novel-rs/cli/assets/156490913/c70f481a-0d67-43f3-b97b-07ffa75a4c91)

It won't let me type anything into the password slot after typing my username, the picture above is what happens if I just press enter and the picture below is where it stops letting me type. Pls help. 

![password](https://github.com/novel-rs/cli/assets/156490913/d176cbac-bf8d-4867-92ce-c3a1de6debf5)

**Comment by TerakomariGandesblood** [comment]
There is no response when entering the password. Just enter the password directly and press Enter.
@FisheadInLukeWarmWater

**Comment by FisheadInLukeWarmWater** [comment]
> There is no response when entering the password. Just enter the password directly and press Enter. @FisheadInLukeWarmWater

I also tried entering my password multiple time and it always gave me the same error message.

**Comment by TerakomariGandesblood** [comment]
> > There is no response when entering the password. Just enter the password directly and press Enter. @FisheadInLukeWarmWater
> 
> I also tried entering my password multiple time and it always gave me the same error message.

I just noticed that the login requirement is to use a mobile phone number or email address, which is the same as the APP requirements.

**Comment by FisheadInLukeWarmWater** [comment]
> > > There is no response when entering the password. Just enter the password directly and press Enter. @FisheadInLukeWarmWater
> > 
> > 
> > I also tried entering my password multiple time and it always gave me the same error message.
> 
> I just noticed that the login requirement is to use a mobile phone number or email address, which is the same as the APP requirements.

That was the issue thx.
