### ISSUE TITLE
 Capturing sfacg Sign-in Bonus Network Packets

### ISSUE THREAD

**Issue by 715494637** [novel-rs/cli#147]
I'm trying to capture network requests for the sfacg sign-in bonus and keep hitting a snag: the app disconnects from the internet when I run packet capture tools on both Android and iOS（ On Android, there’s an SSL certificate error when using packet capture tools. On the iPhone, capturing leads to a no network error.）. Could you shed some light on how to capture these packets successfully?
If direct advice isn't possible, would you consider providing an API interface for the sign-in bonus feature?
![image](https://github.com/novel-rs/cli/assets/93782833/54419bcd-0fb5-48cc-b6d4-b56abab45473)

**Comment by TerakomariGandesblood** [comment]
The client of sfacg has SSL Pinning, and commonly used proxy-based packet capture tools cannot be used directly. On iOS I use Surge; on Android I need to use tools like JustTrustMe, which is more troublesome. In the future I will provide check-in related APIs.
@715494637

**Comment by 715494637** [comment]
Thank you soooo much!！！！！
I'll try it.
@TerakomariGandesblood
