### ISSUE TITLE
Crashing after update 

### ISSUE THREAD

**Issue by FisheadInLukeWarmWater** [novel-rs/cli#164]
Just updated to ver 0.7.7 today and for some reason it's giving me this 
The application panicked (crashed).
Message:  Decryption of encrypted content is not supported
Location: C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\novel-api-0.10.7\src\sfacg\mod.rs:262
![Screenshot 2024-05-24 203420](https://github.com/novel-rs/cli/assets/156490913/27f86074-db15-448e-90e1-ab63ebe69c2d)

**Comment by a464679590** [comment]
me too，not only you

**Comment by a464679590** [comment]
I am now using an old version to download and text encryption appears.Have you ever had this problem?It seems to be sfacg
 newly added text encryption

**Comment by FisheadInLukeWarmWater** [comment]
I tried to go back to the old version I was using, which was 0.5.0. I didn't get anything that mentioned text encryption but a new error. 
![sa](https://github.com/novel-rs/cli/assets/156490913/b69286b5-15ce-44cb-b38f-240dfee9a237)

**Comment by FisheadInLukeWarmWater** [comment]
> I am now using an old version to download and text encryption appears.Have you ever had this problem?It seems to be sfacg newly added text encryption

Just my thoughts as I have no idea how this stuff works but I downloaded something right before doing the update on ver 0.5.0 and it went just fine without error so I don't think sfacg did anything but I could be wrong.

**Comment by a464679590** [comment]
I'm also having trouble with text encryption.Unencrypted content should be previously cached.

**Comment by a464679590** [comment]
I've tested it with multiple accounts and downloaded encrypted text.I'm not sure how to solve this problem. We may have to wait for the author to update this tool.

**Comment by a464679590** [comment]
Encrypted text has been around since today and not yesterday.

**Comment by a464679590** [comment]
Do you have a solution to the text encryption problem

**Comment by FisheadInLukeWarmWater** [comment]
I do not. I have no idea why mine doesn't show an encryption problem.

**Comment by TerakomariGandesblood** [comment]
> I tried to go back to the old version I was using, which was 0.5.0. I didn't get anything that mentioned text encryption but a new error. ![sa](https://private-user-images.githubusercontent.com/156490913/333788047-b69286b5-15ce-44cb-b38f-240dfee9a237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mzk3MDQsIm5iZiI6MTcxNjYzOTQwNCwicGF0aCI6Ii8xNTY0OTA5MTMvMzMzNzg4MDQ3LWI2OTI4NmI1LTE1Y2UtNDRjYi1iMzhmLTI0MGRmZWU5YTIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjE2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGYzZTM3MzFmNzA5MWRkYzU5MjZlMjg4Y2I4YmE4NWU1YmQxNmZkZDdlNTg5NTcxOTBlYjNmNGM1NzE0ODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gutd5_HmvNe0w8OZ4gbS52rLfVFkmMBlkSr22Y9dtr4)

This is due to incompatibility between the old and new versions of the database and configuration files, and the fact that the old version does not have the ability to handle this error.

**Comment by FisheadInLukeWarmWater** [comment]
So it's all an error with the decryption process? Can I do something to fix it or is it some new things sfacg implemented.

**Comment by TerakomariGandesblood** [comment]
> So it's all an error with the decryption process? Can I do something to fix it or is it some new things sfacg implemented.

Yes. Text encryption I'm close to solving, easier than I thought, will release later!

**Comment by TerakomariGandesblood** [comment]
Resolved
