### ISSUE TITLE
请问作者是否可以添加一个下载xirang小说的功能码？

### ISSUE THREAD

**Issue by Zero-114** [novel-rs/cli#170]
息壤app在安卓和IOS端都有发布，之前安卓端用老版本直接缓存可以在应用根目录找到files文件下的bookcahe文件夹直接打开里边就是小说缓存内容可以直接打开，但是现在更新之后老版本直接无法获取小说了，新版本缓存之后是在book_encryption,文件里边内容都加密了。
![5e997f0c3d84ed6896762d59fa9d2b2c](https://github.com/novel-rs/cli/assets/171918345/20ee4431-8b9f-4ab6-a324-ba5769a5246d)
成这个样子了之前是直接显示的小说章节内容，大佬可以考虑添加一下息壤下载功能码，主要是上边的有些小说之后大概率会下架或者和谐内容，所以想本地给保存下来之后万一下架了至少还能看，要是太麻烦就算了。
谢谢

**Comment by TerakomariGandesblood** [comment]
> 息壤app在安卓和IOS端都有发布，之前安卓端用老版本直接缓存可以在应用根目录找到files文件下的bookcahe文件夹直接打开里边就是小说缓存内容可以直接打开，但是现在更新之后老版本直接无法获取小说了，新版本缓存之后是在book_encryption,文件里边内容都加密了。 ![5e997f0c3d84ed6896762d59fa9d2b2c](https://private-user-images.githubusercontent.com/171918345/337193424-20ee4431-8b9f-4ab6-a324-ba5769a5246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjQ4MzgsIm5iZiI6MTcxNzY2NDUzOCwicGF0aCI6Ii8xNzE5MTgzNDUvMzM3MTkzNDI0LTIwZWU0NDMxLThiOWYtNGFiNi1hMzI0LWJhNTc2OWE1MjQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwOTAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjBiYzE0NTM5MDU3Mzg4ZmQxMzYzYmYzMmEwZjFlN2JhNTJkMmRiZmJiZTEzOWRhMTY5Nzg1ODdiZmJkODVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i8gNbnDMZ3WQGzP4a8cMLlk87UfvGZBzr4EWMEKF7us) 成这个样子了之前是直接显示的小说章节内容，大佬可以考虑添加一下息壤下载功能码，主要是上边的有些小说之后大概率会下架或者和谐内容，所以想本地给保存下来之后万一下架了至少还能看，要是太麻烦就算了。 谢谢

我没有使用这个平台，所以暂时没有动力去做这个。[novel-downloader](https://github.com/404-novel-project/novel-downloader)这个项目似乎支持息壤，你看看能不能用。

**Comment by Zero-114** [comment]
好的没事，我就前几个月开始用的息壤看上边的后宫小说，息壤网页端我用的时候就没法看vip章节了，只能手机端看，这个插件用不了。不过也不是啥大问题保存不了就算了。
再次感谢
