### ISSUE TITLE
Request support txt format

### ISSUE THREAD

**Issue by AlexanderHel** [novel-rs/cli#35]
Hi, first I want to thank you for new tool for downloading novels 😄 

Your old tool till work great but ofcourse I would love to use your new tool too.

Hope you can support txt format like the old one.

**Comment by TerakomariGandesblood** [comment]
> Hi, first I want to thank you for new tool for downloading novels 😄
> 
> Your old tool till work great but ofcourse I would love to use your new tool too.
> 
> Hope you can support txt format like the old one.

What do you want to do with the txt file? Read the txt file directly? Then the output in markdown format should meet your needs.

**Comment by AlexanderHel** [comment]
Cause my novels collection mainly contains txt file, just my OCD.

Also I can't read chinese, to read novels I have to use a convert tool to convert to my language.

The tool can only read txt file, obvious I can copy text from markdown format to a txt file and save as it is, but it's an extra step so it's just sweet if the tool can support txt and cover images download separately like before.

No rush just hope it can be add when you're having some free time.

**Comment by TerakomariGandesblood** [comment]
> Cause my novels collection mainly contains txt file, just my OCD.
> 
> Also I can't read chinese, to read novels I have to use a convert tool to convert to my language.
> 
> The tool can only read txt file, obvious I can copy text from markdown format to a txt file and save as it is, but it's an extra step so it's just sweet if the tool can support txt and cover images download separately like before.
> 
> No rush just hope it can be add when you're having some free time.

If this is the case, you can directly modify the file extension, md -> txt.

**Comment by AlexanderHel** [comment]
awesome, thank you very much 😄
