### ISSUE TITLE
It can`t get information from my favourites in ciweimao.

### ISSUE THREAD

**Issue by yizhimengxin2233** [novel-rs/cli#48]
![捕获](https://user-images.githubusercontent.com/58097884/227926580-d14a76d8-5d60-49bc-92c7-be2beb3d51f6.PNG) (with -v)
I tried to run "novel-cli.exe favorites -s ciweimao" to get information about my favorites (or bookshelf?)  in ciweimao.
But it only interrupted by this error: "The novel does not exist".
I don`t know what it means. And I think the program has some bugs.
So how can I deal with it?

**Comment by TerakomariGandesblood** [comment]
I'm guessing you have novels in your bookshelf that have been taken down. The program does not take this into account, I will fix it and release a new version this week.
@yizhimengxin2233
