### ISSUE TITLE
Weird 503 error when downloading a certain book from hbooker

### ISSUE THREAD

**Issue by frank3215** [novel-rs/cli#59]
When running:

```
novel-cli download -v -s ciweimao -f pandoc 100248572
```

The command exited with error:

```
Error: The HTTP request was unsuccessful, status code: `503 Service Unavailable`, message: `Image download failed`
```

I searched the source code, but couldn't find any string matching `Image download failed`...

On other books, the command works fine.

**Comment by TerakomariGandesblood** [comment]
You can try to use the '--no-proxy' option. @frank3215
