### ISSUE TITLE
Can't compile with pandoc on windows?

### ISSUE THREAD

**Issue by frank3215** [novel-rs/cli#63]
When I execute the following command on Windows:

```
novel-cli download -s ciweimao 100334561
novel-cli -v build 赛马娘，开始摆烂.md
```

The program failed with the message:

```
⁨> ⁩ 开始构建 ⁨pandoc⁩ 格式输出
pandoc: images.webp: openBinaryFile: does not exist (No such file or directory)
[32m INFO[0m [2mnovel_cli::cmd::build[0m[2m:[0m Time spent on `pandoc build`: 4289ms
⁨> ⁩ 小说构建完成
[32m INFO[0m [2mnovel_cli[0m[2m:[0m Current physical memory usage: 13.6 MB
```

(The command claimed that it succeeded, but no ePUB file is produced)

To better illustrate the point, the command

```
pandoc 赛马娘，开始摆烂.md -o 赛马娘，开始摆烂.epub
```

failed with

```
pandoc.exe: images.webp: openBinaryFile: does not exist (No such file or directory)
```

and no ePUB file is produced.

However, after I changed all occurrences of `\` to `/` in `赛马娘，开始摆烂.md`, the command worked. Possibly because pandoc unstood backslash `\` incorrectly? If this is the case, perhaps the `download` command should be changed?

**Comment by TerakomariGandesblood** [comment]
Thanks for your feedback, I will fix this this week. @frank3215

**Comment by TerakomariGandesblood** [comment]
Since some problems have not been resolved, I will not release a new version for the time being, you can consider compiling the project yourself
