### ISSUE TITLE
Where is the login information saved and how do I switch accounts?

### ISSUE THREAD

**Issue by Si-JiX** [novel-rs/cli#68]

**Comment by TerakomariGandesblood** [comment]
Password storage: use keychain on macOS; use credential manager on Windows; use secret-service and kernel keyutils on Linux
In addition, cookies or tokens will be saved for login. Regarding the file path, in version 0.2.0, you can run 'novel-cli -V' to view the 'Data Dir'.
To switch users, you need to manually delete the cookie or token file. Features related to multi-user will not be supported.
@Si-JiX
