### ISSUE TITLE
关于build构建生成的epub文件bug

### ISSUE THREAD

**Issue by fuming1227** [novel-rs/cli#75]
![image](https://user-images.githubusercontent.com/58739166/234251339-f6cd5155-f807-4acb-b3a4-5835b7388b2e.png)
![image](https://user-images.githubusercontent.com/58739166/234251470-e836d633-5aea-483b-ac25-99e19057213e.png)
![image](https://user-images.githubusercontent.com/58739166/234252094-ef03a1e6-9920-4468-90a2-20dc6d6de1f0.png)
第二步build之后生成的文件夹内，使用edge浏览器打开html文件，是正常的epub文件一样，但是用zip打包之后，epub阅读软件都不能正常打开。
![image](https://user-images.githubusercontent.com/58739166/234252385-f97b41be-28ca-4945-b2be-efb78f21212e.png)
![image](https://user-images.githubusercontent.com/58739166/234252493-fae9d284-9aba-43d8-a7a3-741efc8cae7d.png)

**Comment by TerakomariGandesblood** [comment]
zip子命令是用来压缩epub文件解压缩后的文件夹，因为有时需要手动修改epub文件，该子命令简化了打包操作。而你这里build之后生成的是mdbook格式的输出。如果你需要epub文件，你需要在执行download时指定--format pandoc，然后再build（注意需要安装pandoc）。
@fuming1227

**Comment by fuming1227** [comment]
![image](https://user-images.githubusercontent.com/58739166/234470847-e290479f-3fa7-451e-8529-884f3ae13b44.png)
报这个错好奇怪，前面下载时有三张图片
![image](https://user-images.githubusercontent.com/58739166/234471063-d1a497b5-bd14-45a6-b72a-6e08c625667a.png)
![image](https://user-images.githubusercontent.com/58739166/234471075-be39632e-ac96-4d0a-bfe1-270706c48152.png)
文件夹名字是images，但是它貌似找的是images.webp？然后并没有任何epub文件输出

**Comment by TerakomariGandesblood** [comment]
等我有时间确认一下。现在该项目在Windows下没有测试过，有很多问题。

**Comment by TerakomariGandesblood** [comment]
@fuming1227

**Comment by fuming1227** [comment]
我最后测试了一下，构建epub时，用到的插图实打实是images文件夹里的，没用的话插图就不在了。然后images.webp这个文件，必须放在和novel-cli.exe一个路径，放在images文件夹是无效的，并且封面实际上用的是这个images.webp图片，可能是封面选择图片这部分代码错了，没有和爬取的封面图片的文件路径对应上。

**Comment by TerakomariGandesblood** [comment]
自定义样式需要写CSS，而我还不会CSS，日后再研究一下。
@whx9986
