### ISSUE TITLE
Support for ciyuanji

### ISSUE THREAD

**Issue by AlexanderHel** [novel-rs/cli#76]
Since some novels only available on ciyuanji app I hope in the future you can support ciyuanji

Or if you know there is anyway can download from ciyuanji can you tell me :D

There is a userscript can use to download but can only work on the web, the novels I'm following only appear on app T_T

**Comment by TerakomariGandesblood** [comment]
I don't know of any other download tools that support ciyuanji.
I was going to support it before, but its app was removed from Apple's App Store, which caused trouble for the analysis interface, because I only have one iPhone available.
In short, I will support ciyuanji when its app is back on the App Store.
@AlexanderHel

**Comment by AlexanderHel** [comment]
Thank you and really happy to heard that

Seems like the app was gone from App Store for a year, wonder what the ios developers are doing

**Comment by VeronicaAlexia** [comment]
> Thank you and really happy to heard that
> 
> Seems like the app was gone from App Store for a year, wonder what the ios developers are doing

I will soon be releasing two open-source projects related to the Ciyuanji novel platform: an app crawler project and a Golang-based third-party API project.

**Comment by AlexanderHel** [comment]
> > Thank you and really happy to heard that
> > Seems like the app was gone from App Store for a year, wonder what the ios developers are doing
> 
> I will soon be releasing two open-source projects related to the Ciyuanji novel platform: an app crawler project and a Golang-based third-party API project.

awesome, just followed your acc hehe

**Comment by TerakomariGandesblood** [comment]
The support of ciyuanji has been basically completed. However, due to the addition/modification of some APIs, some refactoring of the previous code is required, and it will take some time.

**Comment by TerakomariGandesblood** [comment]
Already supported
