### ISSUE TITLE
部分小说epub生成失败

### ISSUE THREAD

**Issue by SkyDream01** [novel-rs/cli#77]
平台windows-x64
在把cover.webp移动至主文件夹并改名images.webp后可以使用novel-cli build生成小说（如：女儿心-sfacg-id：247674）
但部分小说无法生成（如血姬与骑士-sfacg-id：155640）
<img width="856" alt="屏幕截图 2023-04-28 093335" src="https://user-images.githubusercontent.com/86307796/235034404-870f067b-f6fc-4f22-a335-6378a5df24b6.png">

**Comment by TerakomariGandesblood** [comment]
最近比较忙，争取五一修复这几个已知问题。
@SkyDream01

**Comment by TerakomariGandesblood** [comment]
可否提供一下无法生成小说的md文件以及图片，这边没有订阅，无法复现。可以通过邮件发送，邮件地址可以在我的profile中找到。
@SkyDream01

**Comment by TerakomariGandesblood** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/29801775/236169859-984963a8-d7c4-48e2-8c18-b98c1bc7fde7.png">

这里是因为一些特殊的字符构成了一些错误的语法结构，这种情况比较少见，并且在当前使用pandoc的情况下难以自动处理。在遇到该问题时pandoc会忽略该语法结构，事实上该epub生成成功了。如果遇到无法生成的情况，建议手动修改markdown文件。
