### ISSUE TITLE
什么时候更新releases

### ISSUE THREAD

**Issue by SkyDream01** [novel-rs/cli#83]
什么时候更新releases，个人win编译有问题

**Comment by TerakomariGandesblood** [comment]
这周或者下周。Windows上编译由于<https://github.com/cloudflare/boring/issues/109>，需要clang 16以下的版本。
@SkyDream01

**Comment by whx9986** [comment]
![image](https://github.com/novel-rs/cli/assets/58754399/4eab5b70-94ba-4849-8e12-7e2ef9ea7884)
Windows上编译就这样，clang用的15.x版本

**Comment by TerakomariGandesblood** [comment]
看起来是没有设置环境变量。<https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/LLVM-15.0.7-win64.exe> 建议使用这个安装包，重新安装一下，记得选择`set environment variable for all users`。
@whx9986

**Comment by TerakomariGandesblood** [comment]
还不行就手动设置一下'LIBCLANG_PATH'

**Comment by TerakomariGandesblood** [comment]
现在只剩少数几个问题要解决，修复完就会发布新版本。

**Comment by whx9986** [comment]
> 看起来是没有设置环境变量。https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/LLVM-15.0.7-win64.exe 建议使用这个安装包，重新安装一下，记得选择。 @whx9986`set environment variable for all users`

安装的时候是选了这个的，然后不行，但是重启了一下电脑不报这个错了，成功编译了

**Comment by whx9986** [comment]
但是我git clone最新的仓库，还是有[#75](https://github.com/novel-rs/cli/issues/75)提到的bug，仍然需要重命名cover.webp为images.webp并放在md文件同一目录才能build成功epub，看起来这个bug并没有被修复？

**Comment by TerakomariGandesblood** [comment]
![image](https://github.com/novel-rs/cli/assets/29801775/059aee53-9f6a-43cf-bd27-9d4c17883040)
我无法复现这个问题，在我的电脑上运行良好。请运行`novel-cli.exe -V`确定是否是0.2.0版本。
@whx9986

**Comment by TerakomariGandesblood** [comment]
我之前修改过下载保存的逻辑，现在会新创建一个文件夹，图片和md文件在同一文件夹中。

**Comment by whx9986** [comment]
奇怪，我刚git clone的整个仓库，然后cargo install novel-cli构建，为什么还是0.1.4版本

**Comment by TerakomariGandesblood** [comment]
你运行的命令错误，应该是`cargo build --release`。
@whx9986

**Comment by TerakomariGandesblood** [comment]
可以看一下这个的第一章：[trpl](https://kaisery.github.io/trpl-zh-cn/ch01-00-getting-started.html)

**Comment by whx9986** [comment]
原来如此，对这个不是很了解，直接用的readme里提到的cargo install novel-cli命令，谢谢指正

**Comment by TerakomariGandesblood** [comment]
`cargo install`是从<https://crates.io/>下载发布的版本并编译安装，因为我还没有publish新版本，所以就还是旧版。README写得可能不够清楚，有时间我再改改。
@whx9986
