### ISSUE TITLE
0.2.1版本build pandoc到epub失败

### ISSUE THREAD

**Issue by SkyDream01** [novel-rs/cli#85]
0.2.1版本build pandoc到epub失败
命令`novel-cli build 女兒心 pandoc`
<img width="384" alt="屏幕截图 2023-05-19 211142" src="https://github.com/novel-rs/cli/assets/86307796/d5b9cdd2-4a3a-4f4f-a004-8a6341f84c5d">

**Comment by TerakomariGandesblood** [comment]
最后的pandoc是多余的，删掉试试

**Comment by SkyDream01** [comment]
依旧不行，识别为mdbook了
<img width="450" alt="屏幕截图 2023-05-20 085648" src="https://github.com/novel-rs/cli/assets/86307796/7dcbd2f4-c3ba-4562-b671-706ef281e7a1">

**Comment by SkyDream01** [comment]
已解决，谢谢
