### ISSUE TITLE
又是关于书架无法显示的事

### ISSUE THREAD

**Issue by yizhimengxin2233** [novel-rs/cli#98]
在我输入novel-cli bookshelf -s sfacg后，程序先提示我登陆账号，我仅仅输入了账号后，程序就报错

报错内容如下
Error:
   0: error decoding response body: missing field `novelId` at line 1 column 1484
   1: missing field `novelId` at line 1 column 1484

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets

（账号是在旧版本登录并生成缓存的，不知道是不是这个问题）

**Comment by TerakomariGandesblood** [comment]
已确认，sfacg的API：bookshelf_infos不支持获取漫画和声音/视频，当书架中存在两者时会出错。将在未来几天修复。
@yizhimengxin2233
